In [1]:
import get_data as gd
import pandas as pd
import requests
import mdax as md
import os

print("getting MDAX symbols")
mda = md.mdax()

print(mda)

getting MDAX symbols
<mdax.mdax object at 0x10eb355c0>

In [2]:
mda.mdaxData.xs('FRE.DE', level=1, axis=1)

            Adj Close  Close   High    Low   Open     Volume
Date
2009-01-02       8.45  11.83  12.33  11.39  12.33   163248.0
2009-01-05       8.21  11.49  12.00  11.30  12.00   119121.0
2009-01-06       8.49  11.88  12.00  11.54  11.57   121272.0
2009-01-07       8.11  11.35  11.88  11.30  11.88   202644.0
2009-01-08       7.81  10.93  11.37  10.90  11.36   206439.0
2009-01-09       7.92  11.09  11.36  10.88  11.01   113103.0
2009-01-12       7.91  11.06  11.31  10.89  11.14   217122.0
2009-01-13       8.12  11.36  11.43  10.87  11.11   403140.0
2009-01-14       8.34  11.67  11.75  11.42  11.51   136893.0
2009-01-15       8.02  11.22  11.67  11.10  11.45   159774.0
2009-01-16       7.98  11.17  11.64  11.05  11.47   124107.0
2009-01-19       8.22  11.50  11.88  11.22  11.22   119934.0
2009-01-20       8.23  11.52  11.93  11.36  11.42   128595.0
2009-01-21       8.01  11.21  11.48  11.08  11.31   213510.0
2009-01-22       7.98  11.17  11.52  11.07  11.41   248070.0
2009-01-23       7.97  11.15  11.26  10.90  11.17   210225.0
2009-01-24        NaN    NaN    NaN    NaN    NaN        NaN
2009-01-26       8.46  11.84  12.04  11.27  11.27   260661.0
2009-01-27       8.69  12.17  12.39  11.90  11.95   331026.0
2009-01-28       8.71  12.19  12.50  11.99  12.11   242373.0
2009-01-29       8.57  11.99  12.16  11.89  12.16   167772.0
2009-01-30       9.17  12.83  12.99  11.99  11.99   344484.0
2009-02-02       8.91  12.47  13.19  12.33  12.60   205449.0
2009-02-03       9.24  12.94  12.96  12.33  12.66   147834.0
2009-02-04       8.89  12.43  12.79  12.35  12.75   359715.0
2009-02-05       8.98  12.57  12.76  12.48  12.67   148389.0
2009-02-06       9.00  12.59  12.67  12.33  12.67   187452.0
2009-02-09       9.07  12.69  12.82  12.52  12.82    90813.0
2009-02-10       9.16  12.82  13.12  12.64  12.90   248283.0
2009-02-11       9.13  12.77  12.93  12.48  12.48   169821.0
...               ...    ...    ...    ...    ...        ...
2019-04-29      50.71  51.56  51.70  50.67  50.94  1196740.0
2019-04-30      49.75  50.58  51.75  50.42  51.69  1727518.0
2019-05-01        NaN    NaN    NaN    NaN    NaN        NaN
2019-05-02      49.92  50.75  51.80  49.99  50.99  2381547.0
2019-05-03      50.59  51.43  52.32  50.40  50.73  1792419.0
2019-05-06      49.41  50.23  50.42  49.28  50.25  1805033.0
2019-05-07      48.57  49.38  50.42  49.04  50.20  1783786.0
2019-05-08      49.48  50.30  50.30  49.19  49.24  1757599.0
2019-05-09      49.69  50.52  51.04  50.18  50.84  1844474.0
2019-05-10      49.61  50.44  51.85  49.97  51.25  2018819.0
2019-05-13      48.15  48.95  50.50  48.92  50.50  1803643.0
2019-05-14      47.95  48.74  49.40  48.26  49.30  1465296.0
2019-05-15      48.14  48.94  49.01  48.04  48.80  1415942.0
2019-05-16      48.21  49.01  49.10  48.04  48.66  1721212.0
2019-05-17      48.01  48.81  48.88  47.74  48.69  2148516.0
2019-05-20      46.97  46.97  48.42  46.51  48.29  1771311.0
2019-05-21      47.15  47.15  47.50  46.85  46.96  1156849.0
2019-05-22      47.72  47.72  48.43  46.76  46.89  1405181.0
2019-05-23      47.27  47.27  47.83  46.46  47.31  1820444.0
2019-05-24      47.51  47.51  47.85  47.30  47.40  1331532.0
2019-05-27      47.69  47.69  48.38  47.53  47.88   639141.0
2019-05-28      47.75  47.75  48.03  47.24  47.83  1799587.0
2019-05-29      46.34  46.34  47.31  46.27  47.21  1784179.0
2019-05-30      46.10  46.10  46.62  46.01  46.56   843001.0
2019-05-31      45.41  45.41  45.50  44.33  45.42  1870069.0
2019-06-03      45.91  45.91  45.91  44.87  45.16  1317813.0
2019-06-04      46.83  46.83  46.97  45.18  45.47  1636866.0
2019-06-05      46.69  46.69  47.37  46.69  46.98  1626100.0
2019-06-06      45.96  45.96  46.91  45.63  46.85  1611553.0
2019-06-07      45.90  45.90  46.19  45.55  45.92  1339794.0

[2664 rows x 6 columns]

In [4]:
mda.mdaxData.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2664 entries, 2009-01-02 to 2019-06-07
Columns: 174 entries, (Adj Close, 1COV.DE) to (Volume, WDI.DE)
dtypes: float64(174)
memory usage: 3.6 MB